tasks:
  - task_id: task_1
    sql: test_1.sql

  - task_id: task_2
    sql: test_2.sql

  - task_id: task_3
    sql: test_3.sql  
    
  - task_id: task_4
    sql: test_4.sql     
    depends_on: 
      - task_1
      - task_2
      - task_3